SistemaSaudeAspNetMVC/Models/Cliente.cs
using System.ComponentModel.DataAnnotations;

namespace SistemaSaudeAspNetMVC.Models
{
    public class Cliente
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Nome { get; set; }
        public string Email { get; set; }
    }
}

SistemaSaudeAspNetMVC/Models/ErrorViewModel.cs
namespace SistemaSaudeAspNetMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SistemaSaudeAspNetMVC/Models/Medicos.cs
using System.ComponentModel.DataAnnotations;

namespace SistemaSaudeAspNetMVC.Models
{
    public class Medicos
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Nome { get; set; }
        public string Especializacao { get; set; }
        
    }
}

SistemaSaudeAspNetMVC/Controllers/ClienteController.cs
using Microsoft.AspNetCore.Mvc;
using SistemaSaudeAspNetMVC.Data;
using SistemaSaudeAspNetMVC.Models;

namespace SistemaSaudeAspNetMVC.Controllers
{
    public class ClienteController : Controller
    {
        private readonly ApplicationDbContext _db;

        public ClienteController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<Cliente> objMedicosList = _db.Clientes;

            return View(objMedicosList);
        }
    }
}

SistemaSaudeAspNetMVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SistemaSaudeAspNetMVC.Models;
using System.Diagnostics;

namespace SistemaSaudeAspNetMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SistemaSaudeAspNetMVC/Controllers/MedicoController.cs
using Microsoft.AspNetCore.Mvc;
using SistemaSaudeAspNetMVC.Data;
using SistemaSaudeAspNetMVC.Models;

namespace SistemaSaudeAspNetMVC.Controllers
{
    public class MedicoController : Controller
    {
        private readonly ApplicationDbContext _db;

        public MedicoController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<Medicos> objMedicosList = _db.Medicos;

            return View(objMedicosList);
        }
    }
}

SistemaSaudeAspNetMVC/Views/Cliente/Index.cshtml
@model IEnumerable<Cliente>
@{
    ViewData["Title"] = "Index";
}

<h1>Index medicos</h1>
<a asp-controller="Medico" asp-action="Create">Cadastro de Cliente</a>
<table class="table table-brodered table-striped" style="width:100%">
    <thead>
        <tr>
            <th>
                Nome do Cliente
            </th>
            <th>
                Email
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var obj in Model)
        {
            <tr>
                <td width="50%">
                    @obj.Nome
                </td>
                <td width="50%">
                    @obj.Email
                </td>
            </tr>
        }
    </tbody>
</table>

SistemaSaudeAspNetMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

SistemaSaudeAspNetMVC/Views/Index.cshtml
@page
@model SistemaSaudeAspNetMVC.Views.IndexModel
@{
}

SistemaSaudeAspNetMVC/Views/Medico/Index.cshtml
@model IEnumerable<Medicos>
@{
    ViewData["Title"] = "Index";
}

<h1>Index medicos</h1>
<a asp-controller="Medico" asp-action="Create">Cadastro de medico</a>
<table class="table table-brodered table-striped" style="width:100%">
    <thead>
        <tr>
            <th>
                Nome do medico
            </th>
            <th>
                Especializacao
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var obj in Model)
        {
            <tr>
                <td width="50%">
                    @obj.Nome
                </td>
                <td width="50%">
                    @obj.Especializacao
                </td>
            </tr>
        }
    </tbody>
</table>

SistemaSaudeAspNetMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SistemaSaudeAspNetMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SistemaSaudeAspNetMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SistemaSaudeAspNetMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Medico" asp-action="Index">Medicos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cliente" asp-action="Index">Clientes</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - SistemaSaudeAspNetMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>